### ISSUE TITLE
bassasio.dll not found and no signal at ASIO Input source

### ISSUE THREAD

**Issue by chmod755a** [pkviet/obs-asio#10]
I followed the instructions to build the plugin with bassasio.  I was able to compile obs-studio as well as obs-asio with no errors.  

I copied obs-asio.dll and bassasio.dll to obs-studio/obs-plugins/64bit as instructed but when I start obs, the log file says:
"20:51:15.685: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/bassasio.dll' not found, loading of module failed"

I'm still able to add an ASIO Input source, assign a device (X18 ASIO driver), set OBS Channel 1 to "X18 ASIO Driver 0 In 1".

I have a microphone hooked up to channel 1 on my Behringer XR18 mixer.  I can see that there's a signal sent to the computer but in OBS, the ASIO Input source shows no signal.

I wonder if this is related.

If I use the rtaudio version of the plugin, I have no issues, so I'm sure the problem is plugin related.

Log file is attached.

[2019-02-07 20-51-14.txt](https://github.com/pkviet/obs-asio/files/2843650/2019-02-07.20-51-14.txt)

**Comment by pkviet** [comment]
hi,
Firstly, I'm using in prod the XR18 with the obs-asio plugin (bassasio version); i've never had any issue. It works perfectly and is very reliable.
This message: "20:51:15.685: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/bassasio.dll' not found, loading of module failed"
is not a problem.
It just means that bassasio.dll is found but is not an obs plugin. Which is the case. The plugin is obs-asio.dll while bassasio.dll is the library used by obs-asio to enable asio.
From looking at your log, the obs-asio.dll is there, the XR18 is discovered.
Are you trying to use the XR18 in another software ?
asio forbids that. It is an exclusive protocol. So you can't have a daw open at the same time.
That's my best guess.
If you want to use the XR18 in a daw like reaper, then you'll have to use virtual audio drivers (like rearoute provided in reaper) with the following setup: XR18 captured in reaper ==> output to rearoute virtual asio driver ==> captured by obs-asio plugin in obs.
In my prod setups, i don't use a daw, i mix in the XR18 directly but set the USB sends to the buses.
In obs, i can therefore capture the buses.
For further support, ping me (pkv) or andersama (the other author) on obs discord. We're listed in hte devs list . We'll need more info.
