### ISSUE TITLE
Does not work with Audient iD14 ASIO Drivers

### ISSUE THREAD

**Issue by yokaiichi** [pkviet/obs-asio#12]
Everything installs fine and I can see and configure everything associated with the Audient ASIO driver for the iD14, but no sound actually comes into OBS on that source.

**Comment by pkviet** [comment]
please provide at least a log! How can you expect the authors of this free plugin to provide help without a minimum of infos ?
Be aware that asio devices are exclusive. If you have another application using the device it will prevent obs to use it.

**Comment by yokaiichi** [comment]
If you can tell me where to look for the logs, and which specific files you want, I'd be happy to do that.

**Comment by pkviet** [comment]
Look in Menu > Help >logs
For further troubleshooting you can ping me (@pkv) or the other author @Andersama on obs discord.

**Comment by pkviet** [comment]
closing due to no further comments; re-open if the issue persists
