### ISSUE TITLE
OBS only finding input

### ISSUE THREAD

**Issue by chrissyast** [pkviet/obs-asio#13]
Apologies if I've misunderstood what this plugin is for but:

I use a DAW to record and produce music. I want the output going to OBS. However with this plugin the only options I have in OBS are for the ASIO inputs (i.e. the raw sound from my instruments). Is it not possible to record the _output_ in OBS?

**Comment by pkviet** [comment]
hello
yes the plugin provides Asio INPUTS capture; this is as it should be: in a daw when you select a device are you able to capture its outputs ? No unless you use workarounds.
This is not peculiar to asio : to capture audio outputs with any audio devices requires that the driver provides this capability. For instance, soundBlaster devices have long had a 'What You Hear' capture device which routes the output to inputs.
There are workarounds to capture audio outputs, basically use virtual audio drivers :
- on mac, you can use soundflower / loopback;
- on windows, you have voicemeeter, virtual audio cable, etc.
Specifically for asio, you need an asio compatible virtual audio driver:
- some are provided by DAWS like reaper or FLStudio.
- for instance, Reaper installs Rearoute driver. It appears as an additional asio device to which one can output audio. This audio is then routed internally to the inputs of Rearoute virtual asio device and can be captured by obs-studio through the obs-asio plugin.
Another solution is that some asio devices have quite convenient drivers which provide internal routing.
For instance the XR18 can route any mix bus to an input. Meaning that you can capture your mix in obs-studio. This is what I use in prod.
You might want to try Reaper + rearoute or FL Studio, whichever works fine. Maybe there are other daws which provide virtual drivers. Can't say.

**Comment by chrissyast** [comment]
Understood, thank you.

**Comment by qreon** [comment]
Hello :) Do you mind elaborating on how FL Studio allows you to capture an audio output?

**Comment by pkviet** [comment]
i don't own FLStudio so can't elaborate; but users reported to us that it had a virtual driver and worked fine with our plugin

**Comment by qreon** [comment]
In the meantime I found out FL Studio provides the "FL Studio ASIO" virtual driver which indeed sends the output of ASIO devices on Windows' main audio output. However it introduces a small but annoying amount of latency to the input. I kept looking for something else but I think that's about the only possible way without resorting to 3rd party stuff.  
Thank you for your answer. :)
