### ISSUE TITLE
OBS Studio 23.1.0 won't load asio plugin 1.3.2

### ISSUE THREAD

**Issue by CHEF-KOCH** [pkviet/obs-asio#14]
OBS Studio: 23.0.1 (Windows Build tested with 1803 + 1903 / Linux Xubuntu)
Plugin version: asio plugin 1.3.2
Workaround: use version 1.3.1 (which works for me).

Debug log

```
//OBS log
LoadLibrary failed for '../../obs-plugins/64bit/obs-asio.dll': The specified module could not be found.
 (126)
Module '../../obs-plugins/64bit/obs-asio.dll' not loaded
```

**Comment by pkviet** [comment]
very odd, i can't repro. Stick to 1.3.1 then. And if you can drop a log it would be welcome.

**Comment by 1v4r** [comment]
I have the same problem with 1.3.2 on 23.1.0 Works great with 1.3.1

**Comment by derVodi** [comment]
Me too.

**Comment by pkviet** [comment]
thanks all, i'm removing 1.3.2
