### ISSUE TITLE
Higher sample rate than 48khz possible?

### ISSUE THREAD

**Issue by TheRealDadbeard** [pkviet/obs-asio#15]
Any plans to implement that so I can use all of my devices at 96khz? As it's ASIO it has to be the same everywhere or is this a limitation of OBS since it only supports 48khz? Either way it would just downsample the higher quality one.

**Comment by pkviet** [comment]
Yes, it's an obs limitation. Do you actually hear a difference between 96 khz and 48 khz?  Just curious. I know studios record at sampling rates larger than 48 khz but mathematically this makes no sense due to shannon theorem.

**Comment by TheRealDadbeard** [comment]
Yeah you hear it. Using Stereo Direct on my Soundblaster Z with 192khz @ 24bit makes a hearable difference, at least for me, even on lower res files. Ah well at least I can use ASIO and bypass all that Windows Soundstack junk. Using my input device directly gives me much worse audio than ASIO. It's just much clearer and not that muffled so thx for this plugin!
