### ISSUE TITLE
Cannot Pick Up Virtual Audio Cables

### ISSUE THREAD

**Issue by MrTeeXD** [pkviet/obs-asio#16]
So i have the latest version of the OBS ASIO plugin (1.3.1) but it does not seem to pick virtual audio cables and it shows that there's no device active. Here are some screenshots taken of this error :

![obs64_XRXDg2UgxX](https://user-images.githubusercontent.com/37266538/58707661-d78a6000-83b5-11e9-9cb1-61e7c74036a3.png)
![obs64_bWqGIeMlia](https://user-images.githubusercontent.com/37266538/58707662-d822f680-83b5-11e9-87db-017c595f2826.png)

**Comment by pkviet** [comment]
which virtual audio cables are you using ? 
the most well-known from eugene muzychenko [here](https://vac.muzychenko.net/en/) are not asio so they can't work.
These are not either: [from VB cable](https://www.vb-audio.com/Cable/)
So if you want to route to asio from another app, make sure that the app and the virtual cable are asio compatible.
This would work fromr eaper to obs using the rearoute virtual driver for instance.

**Comment by MrTeeXD** [comment]
Alright, i'm going to try ReaRoute to see if it works
