### ISSUE TITLE
Same card multiple OBS instances

### ISSUE THREAD

**Issue by sraptis** [pkviet/obs-asio#17]
Hi,
this is not a bug, but probably a usage issue.
I have a Marian A3 card and I am using multiple instances (portable) of OBS to stream different ADAT -> ASIO channels. The thing is that using the default build only the first instance has audio.
Which version should I build to have this functionality?

Thank you in advance,

Stavros

**Comment by pkviet** [comment]
mmh try building with bassasio (untested though) but it should be multiclient and multidevice; 
another possibility would be to use a daw like reaper: create your different tracks there and add hardware sends to its Rearoute virtual driver.
In the various obs instances you just need then to capture with asio plugin to a specific rearoute track.

**Comment by sraptis** [comment]
Thank you,

I will build bassasio and try. My first choice is not to use any software in between.

Regards,

Stavros

**Comment by sraptis** [comment]
FYI, it didn't work. I compiled with bassasio 1.4
So I resorted to the routing functionality of Marian drivers.

Thank you again for your effort
