### ISSUE TITLE
Does not detect UAD Apollo Twin USB

### ISSUE THREAD

**Issue by jbehrmusic** [pkviet/obs-asio#18]
I read somewhere that UAD devices may work with bassasio, but I have no coding experience. Is there some version that you have created (of bassasio) that I can try to use with my UAD Apollo Twin USB?

**Comment by pkviet** [comment]
Nope. I'm not allowed per GPL terms to distribute the bassasio version.
Sorry ...

**Comment by jbehrmusic** [comment]
Is there a guide or something that I can follow to try and do it myself? I basically cannot use OBS without it. Unless I buy a completely separate Audio Interface... Do you have a list of interfaces that will work with OBS-ASIO? For example, there are many Behringer audio interfaces that are less than $40. Does your OBS-ASIO work with those interfaces?

**Comment by pkviet** [comment]
On Sat, Jun 22, 2019, 07:27 jbehrmusic <notifications@github.com> wrote:

> Is there a guide or something that I can follow to try and do it myself?
>
Check the readme.

> I basically cannot use OBS without it. Unless I buy a completely separate
> Audio Interface... Do you have a list of interfaces that will work with
> OBS-ASIO?
>
Check the Release section for a list of tested devices.

> For example, there are many Behringer audio interfaces that are less than
> $40. Does your OBS-ASIO work with those interfaces?
>
No idea. If they use asio4all forget them.

A workaround to keep your device would be to use some daw like reaper or fl
studio and use their virtual driver to route audio to obs-asio.

**Comment by jbehrmusic** [comment]
Thanks for the reply. I think the main issue is getting the microphone to work properly. Can I also use the virtual drivers to route my mic?

**Comment by pkviet** [comment]
On Sat, Jun 22, 2019, 07:47 jbehrmusic <notifications@github.com> wrote:

> Thanks for the reply. I think the main issue is getting the microphone to
> work properly. Can I also use the virtual drivers to route my mic?
>

Yes. All inputs can be routed.

**Comment by jbehrmusic** [comment]
I figured out how to route everything through Voicemeter Banana. Thanks for the fast replies.
