### ISSUE TITLE
Do I need to use your obs-studio fork to build bassasio and can I use v14?

### ISSUE THREAD

**Issue by lagauche** [pkviet/obs-asio#19]
I noticed your build directions ask to git clone obs-studio from your fork. Can I git clone directly from the obs github to get the latest version and can I use bassasio14? your link downloads the older bassasio13

Thanks! I'm new to building but hoping I can get this working.

**Comment by pkviet** [comment]
nope you don't need my obs-studio fork; you only need it if you want to build both obs and the plugin at the same time. You can also compile the plugin as a stand alone, it's explained in the instructions. The latter requires though that you have libobs library compiled so you might as well compile everything...
I think I'll try to provide libobs lib in a deps folder to easen the compilation.
I had not seen the new version of bassasio. I'll check it to see if it works.

**Comment by pkviet** [comment]
update:
i've checked that you can drop in bassasio 1.4 without issues.
I'll provide the obs lib and dll; this will make the compilation easier.

**Comment by pkviet** [comment]
update 2:
- compilation instructions updated ==> check the wiki
- I now provide the libobs dll and lib so a stand alone compilation should be easier
The compilation time  itself is only 10-20 seconds on visual studio ... The setup is what takes time...
Report here if you have difficulties or ping me on obs-studio discord.

**Comment by lagauche** [comment]
Thanks, I reached out on Discord. I'm running into errors when configuring i
![Capture](https://user-images.githubusercontent.com/32005683/60391946-13edd080-9ac8-11e9-8d94-a4fcd98d00ce.PNG)
n cmake-gui

I don't think it matters, but I am configuring using visual studio 2019. I got the same error when I tried on a friend's computer using 2015 also.

Any idea how to fix these errors in the image?

**Comment by lagauche** [comment]
Hey Thanks for the info so far. I'm experimenting to get this working. If I build to plugin standalone using bassasio can I use that plugin with the installer download version OBS offers? 

Trying to figure out why i'd even want to build OBS itself?

**Comment by pkviet** [comment]
sorry i forgot some steps in the wiki for stand-alone compilation:
- in obs-studio folder, create a build folder
- with cmake, configure and generate after setting QTDIR and DepsPath per build instructions of obs-studio
- you won't have to compile obs-studio though since I uploaded the lib and dll;
- just create a folder RelWithDebInfo in obs-studio/build/libobs/RelWithDebInfo and put there: obs.lib which is in obs-asio/deps/libobs folder.
- you can then compile obs-asio with VS 2019 or 2017

**Comment by lagauche** [comment]
Gotcha, do I still need to include this in the cmake variables since you now include it: "LIBOBS_INCLUDE_DIR (path) : location of the libobs subfolder in the source code of OBS Studio; for instance for me it is C:/obs-studio/libobs"

?

**Comment by lagauche** [comment]
Ah sorry for all the questions. Right now, I generated obs-studio and am tryiing to generate the obs-asio plugin, but getting this WARNING. Should I ignore or am I doing something wrong? I believe that's the BASS_ASIO_LIB variable and i have it set to path. Should i change to file name?
![linking](https://user-images.githubusercontent.com/32005683/60393756-2c6de300-9ae8-11e9-9229-d148361af9e4.JPG)

**Comment by lagauche** [comment]
I have the plugin working now but now sure if I broke did anything wrong. A couple things I have to do different than your directions:

1)
I had to put obs.lib in ...obs-studio\build\libobs\Debug instead of "RelWithDebInfo" because this exists nowhere for me in any of my builds or anywhere : /

2)
I had to change the BASS_ASIO_LIB var to filepath because as my error in my last reply shows, i couldn't link to the library unless i actually selected it.

The only error i got while building the obs-asio plugin in VS2019 after those two steps is "MSB3073 The Command "Setlocal" 

I think this is some kind of permissions error so I just ignored it and I found the .dll I needed in the build folder.

**Comment by pkviet** [comment]
On Sun, Jun 30, 2019, 10:14 La Gauche <notifications@github.com> wrote:

> I have the plugin working now but now sure if I broke did anything wrong.
> A couple things I have to do different than your directions:
>
>    1.
>
> I had to put obs.lib in ...obs-studio\build\libobs\Debug instead of
> "RelWithDebInfo" because this exists nowhere for me in any of my builds or
> anywhere : /
>
You have to create the folder

>
>    1.
>
> I had to change the BASS_ASIO_LIB var to filepath because as my error in
> my last reply shows, i couldn't link to the library unless i actually
> selected it.
>
Not at my PC but you're probably right.

> The only error i got while building the obs-asio plugin in VS2019 after
> those two steps is "MSB3073 The Command "Setlocal"
>
In vs studio in build menu, clean and rebuild

**Comment by lagauche** [comment]
I did create the "RelWithDebInfo" folder and put obs.lib in it, but if my memory serves me, VS gave me a build error saying it was looking for obs.lib here "obs-studio\build\libobs\Debug" but it could not find it. It was not aware of "RelWithDebInfo". Also the obs-asio build has three projects ALL_BUILD, obs-asio and ZERO-CHECK. There is no "RelWithDebInfo". 

I remember a couple days ago i tried to to build OBS with the plugin and I did see that folder that's why I mention. I don't think it exists for me when just building the plugin.

**Comment by pkviet** [comment]
you're probably building obs-asio in debug, that's why. Try in RelWithDebInfo (release with debug info).

**Comment by pkviet** [comment]
on second thought, i think that providing the obs.lib and obs.dll files creates more confusion than it helps in the build instructions. So I've updated the instructions by requiring to compile obs-studio. This will be simpler for setting the paths. Sorry about this back and forth.

**Comment by pkviet** [comment]
Try to catch me on discord.
This will be easier.
We have some misunderstandings here.

**Comment by pkviet** [comment]
closing since the user managed to compile
