### ISSUE TITLE
Doesnt work on Focusrite Scarlett 2i4 1st gen

### ISSUE THREAD

**Issue by ariomester** [pkviet/obs-asio#21]
Ive tested OBS ASIO on both Focusrite Saffire 40 and Scarlett 2i4, using Studio One. On Saffire it worked only via hardwired SPDIF loop and doesnt worked on Scarlett. Even addressing the 4 outputs of Scarlett OBS ASIO doenst got it at all.

**Comment by pkviet** [comment]
You're very confused on what the plugin does.
If you connect a saffire and set up a daw, like studio one or reaper, would
you expect that the said daw captures inputs or outputs ? The daw will
capture inputs. It  never captures outputs. You send audio to outputs and
receive audio from inputs.
Obs-asio plugin adds asio capture capability to obs-studio , meaning it
allows one to capture inputs from an asio capable device.
It's as it should be. You're capturing what comes in, a mike, a guitar.
You're not capturing what another software is sending out to the speakers
...
There are however workarounds relying on virtual audio drivers.
Check the wiki section on "Capturing mixes"
