### ISSUE TITLE
Doesn`t work with Tascam US-322

### ISSUE THREAD

**Issue by Dante1349** [pkviet/obs-asio#25]
Hey, i have problems with the mentioned device. These are the settings, maybe i have to switch to 24bit in OBS, but this isn´t possible.
device properties:
![image](https://user-images.githubusercontent.com/9164492/63227443-ec250a00-c1e6-11e9-847a-fc9d9b1c0b8b.png)
obs settings:
![image](https://user-images.githubusercontent.com/9164492/63227465-373f1d00-c1e7-11e9-9098-549eecd1df20.png)

Can you help me with that?

**Comment by pkviet** [comment]
The buffer is quite small.
Try 1024, then decrease to 512 , 256 etc If you use a mike, it's not
captured ?
Drop a screenshot of the mixer.
I want to check the number of channels displayed. It should be 2 channels
if capture is working.

**Comment by Dante1349** [comment]
this isn´t possible either:
![image](https://user-images.githubusercontent.com/9164492/63227581-3a86d880-c1e8-11e9-8367-53efd8fec2d7.png)
seems that it is not working, cause i just have one channel here:
![image](https://user-images.githubusercontent.com/9164492/63227597-4f636c00-c1e8-11e9-8630-2207b56e7d3c.png)

**Comment by Dante1349** [comment]
we can do a screen sharing if you got time, im also a developer, maybe i can help

**Comment by pkviet** [comment]
From the screenshot i see two channels for asio input source (it's just
that no mike is connected i bet OR that you've opened another app).
So obs-asio plugin seems ok, it is capturing.
Drop the log but imo if audio doesn't reach obs something else is going on.

**Comment by Dante1349** [comment]
hmm ok, maybe that is the problem. im trying to record the audio from the asio soundcard, that cubase is using. but this should be possible or am i wrong?

**Comment by pkviet** [comment]
Ok that's why. Can't work because asio is exclusive. This is a limitation
of asio sdk: a single app only can capture at a time.
Some drivers workaround that and are multi clients (ex:  rme) but most asio
drivers can't.
Check the wiki for a way to bypass
that by using virtual audio drivers.
Works with daws like reaper.
But not cubase afaik.

**Comment by Dante1349** [comment]
You´re right. I missunderstood the functionality of the plugin. Sorry for the inconvenience. I figuered out how to solve my problem in the meantime. Thanks for your help either @pkviet =) 

And this is what i did to record my cubase asio sound in OBS:

* Install [Voicementer](https://www.vb-audio.com/Voicemeeter/)
* Use Voicemeter as ASIO device in Cubase
* Add Voicemeter as Audio Input Source in OBS
