### ISSUE TITLE
OBS can`t shut down with plugin asio

### ISSUE THREAD

**Issue by ApostolDmitry** [pkviet/obs-asio#3]
Before posting an Issue, make sure that:
- you've read the wiki especially the Install and Usage section, the Troubleshooting section, the Capturing mixes section.
- you've researched the issues to find if there aren't similar issues which have been posted already.
- have an obs log ready (obs-studio : help menu > log > see current log)

**Plugin Version**
Which release of the plugin are you using?

I'm using 4.0.1

**Describe the bug**
It's just that OBS can't shut down before exit for him

**To Reproduce**
1. Just open obs with plugin
2. add your device
3. And Shut down OBS 
4. And finally we see the result, obs cannot shut down

**Expected behavior**
OBS can shut down with plugin 

**Screenshots**
https://drive.google.com/file/d/1s4jpTD5K61rNt45DQslK4W6djE8FPWjp/view?usp=sharing

just freezes in this moment 

**Additional context**

```
09:09:41.958: ==== Shutting down ==================================================
09:09:42.000: WASAPI: Device '(2- Logitech G733 Gaming Headset)' Terminated
09:09:42.002: WASAPI: Device '' Terminated
09:09:42.012: WASAPI: Device '' Terminated
```
and log before down

**Comment by pkviet** [comment]
Please provide me with a full log.
If you revert to v4.0.0 , you don't have any issue?

**Comment by pkviet** [comment]
I obviously can't reproduce so I'll need way more info on your side. 
What's the asio device ?
Does it happen consistently, every single time you use obs ?
Can you repro on a clean build ? Portable mode on an initially blank scene where you've added an asio source ?

**Comment by ApostolDmitry** [comment]
@pkviet  Yes. There is no problem disabling the program on 4.0.0

**Comment by ApostolDmitry** [comment]
@pkviet  Full log on clean obs (4.0.1): 

```
18:58:51.821: CPU Name: AMD Ryzen 9 5950X 16-Core Processor            
18:58:51.821: CPU Speed: 3400MHz
18:58:51.821: Physical Cores: 16, Logical Cores: 32
18:58:51.821: Physical Memory: 32669MB Total, 14214MB Free
18:58:51.821: Windows Version: 10.0 Build 22631 (release: 23H2; revision: 2861; 64-bit)
18:58:51.821: Running as administrator: false
18:58:51.821: Windows 10/11 Gaming Features:
18:58:51.821: 	Game DVR: On
18:58:51.821: 	Game Mode: Probably On (no reg key set)
18:58:51.822: Sec. Software Status:
18:58:51.823: 	Антивирусная программа Microsoft Defender: enabled (AV)
18:58:51.824: 	Брандмауэр Windows: enabled (FW)
18:58:51.824: Current Date/Time: 2023-12-29, 18:58:51
18:58:51.824: Browser Hardware Acceleration: true
18:58:51.824: Hide OBS windows from screen capture: false
18:58:51.824: Qt Version: 6.5.3 (runtime), 6.5.3 (compiled)
18:58:51.824: Portable mode: false
18:58:51.962: OBS 30.0.2 (64-bit, windows)
18:58:51.962: ---------------------------------
18:58:52.015: ---------------------------------
18:58:52.015: audio settings reset:
18:58:52.015: 	samples per sec: 48000
18:58:52.015: 	speakers:        2
18:58:52.015: 	max buffering:   960 milliseconds
18:58:52.015: 	buffering type:  dynamically increasing
18:58:52.016: ---------------------------------
18:58:52.016: Initializing D3D11...
18:58:52.016: Available Video Adapters: 
18:58:52.018: 	Adapter 0: NVIDIA GeForce RTX 4070 Ti
18:58:52.018: 	  Dedicated VRAM: 12593397760 (11.7 GiB)
18:58:52.018: 	  Shared VRAM:    17128343552 (16.0 GiB)
18:58:52.018: 	  PCI ID:         10de:2782
18:58:52.018: 	  HAGS Status:    Enabled (Default: No, Driver status: Supported)
18:58:52.018: 	  Driver Version: 31.0.15.4617
18:58:52.019: 	  output 0:
18:58:52.019: 	    name=LS24AG30x
18:58:52.019: 	    pos={0, 0}
18:58:52.019: 	    size={1920, 1080}
18:58:52.019: 	    attached=true
18:58:52.019: 	    refresh=144
18:58:52.019: 	    bits_per_color=8
18:58:52.019: 	    space=RGB_FULL_G22_NONE_P709
18:58:52.019: 	    sdr_white_nits=80
18:58:52.019: 	    nit_range=[min=0.500000, max=270.000000, max_full_frame=270.000000]
18:58:52.019: 	    dpi=96 (100%)
18:58:52.019: 	    id=\\?\DISPLAY#SAM7179#5&2ed8f912&0&UID33025#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
18:58:52.019: 	    alt_id=\\.\DISPLAY1
18:58:52.019: 	  output 1:
18:58:52.019: 	    name=22B1W
18:58:52.019: 	    pos={-1920, 0}
18:58:52.019: 	    size={1920, 1080}
18:58:52.019: 	    attached=true
18:58:52.019: 	    refresh=60
18:58:52.019: 	    bits_per_color=8
18:58:52.019: 	    space=RGB_FULL_G22_NONE_P709
18:58:52.019: 	    sdr_white_nits=80
18:58:52.019: 	    nit_range=[min=0.500000, max=270.000000, max_full_frame=270.000000]
18:58:52.019: 	    dpi=96 (100%)
18:58:52.019: 	    id=\\?\DISPLAY#AOC2201#5&2ed8f912&0&UID33024#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
18:58:52.019: 	    alt_id=\\.\DISPLAY2
18:58:52.020: Loading up D3D11 on adapter NVIDIA GeForce RTX 4070 Ti (0)
18:58:52.095: D3D11 loaded successfully, feature level used: b000
18:58:52.095: DXGI increase maximum frame latency success
18:58:52.095: Hardware-Accelerated GPU Scheduling enabled on adapter!
18:58:52.095: D3D11 GPU priority setup failed (not admin?)
18:58:52.169: ---------------------------------
18:58:52.169: video settings reset:
18:58:52.169: 	base resolution:   1920x1080
18:58:52.169: 	output resolution: 1920x1080
18:58:52.169: 	downscale filter:  Bicubic
18:58:52.169: 	fps:               60/1
18:58:52.169: 	format:            NV12
18:58:52.169: 	YUV mode:          Rec. 709/Partial
18:58:52.169: NV12 texture support enabled
18:58:52.169: P010 texture support not available
18:58:52.171: Audio monitoring device:
18:58:52.171: 	name: По умолчанию
18:58:52.171: 	id: default
18:58:52.171: ---------------------------------
18:58:52.173: No AJA devices found, skipping loading AJA UI plugin
18:58:52.173: Failed to initialize module 'aja-output-ui.dll'
18:58:52.174: No AJA devices found, skipping loading AJA plugin
18:58:52.174: Failed to initialize module 'aja.dll'
18:58:52.174: Skipping module '../../obs-plugins/64bit/chrome_elf.dll', not an OBS plugin
18:58:52.176: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
18:58:52.177: Failed to load 'en-US' text for module: 'decklink-captions.dll'
18:58:52.177: Failed to load 'en-US' text for module: 'decklink-output-ui.dll'
18:58:52.179: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
18:58:52.179: Failed to initialize module 'decklink.dll'
18:58:52.185: Skipping module '../../obs-plugins/64bit/libcef.dll', not an OBS plugin
18:58:52.185: Skipping module '../../obs-plugins/64bit/libEGL.dll', not an OBS plugin
18:58:52.185: Skipping module '../../obs-plugins/64bit/libGLESv2.dll', not an OBS plugin
18:58:52.741: [asio source]: Querying installed ASIO drivers.
18:58:52.741: 
18:58:52.741: [asio source]: Found ASIO driver: SERIES 102i/208i ASIO with CLSID {976C0E77-ACF7-47CB-8395-71E8BB227A89}
18:58:52.741: 
18:58:52.741: [asio source]: Found ASIO driver: US-HR Series ASIO with CLSID {0B895135-3E37-418F-86F4-688ED2789606}
18:58:52.741: 
18:58:52.741: [asio source]: ASIO Info: Done querying ASIO drivers.
18:58:52.741: [asio source]: plugin loaded successfully (version @CMAKE_PROJECT_VERSION@)
18:58:52.752: [obs-browser]: Version 2.22.2
18:58:52.752: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.0.0-5060-shared-textures.2594+gc69ad37+chromium-103.0.5060.134 (compiled)
18:58:52.756: NVENC supported
18:58:52.900: [noise suppress]: NVIDIA denoiser disabled, redistributable not found or could not be loaded.
18:58:52.901: Failed to get NVVideoEffects.dll version info size
18:58:52.901: [NVIDIA VIDEO FX]: FX disabled, redistributable not found or could not be loaded.
18:58:52.937: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.3.4 | RPC Version: 1)
18:58:52.937: [obs-websocket] [obs_module_load] Qt version (compile-time): 6.5.3 | Qt version (run-time): 6.5.3
18:58:52.937: [obs-websocket] [obs_module_load] Linked ASIO Version: 102800
18:58:52.942: [obs-websocket] [obs_module_load] Module loaded.
18:58:52.948: [vlc-video]: VLC 3.0.20 Vetinari found, VLC video source enabled
18:58:52.954: ---------------------------------
18:58:52.954:   Loaded Modules:
18:58:52.954:     win-wasapi.dll
18:58:52.954:     win-dshow.dll
18:58:52.954:     win-capture.dll
18:58:52.954:     vlc-video.dll
18:58:52.954:     text-freetype2.dll
18:58:52.954:     rtmp-services.dll
18:58:52.954:     obs-x264.dll
18:58:52.954:     obs-websocket.dll
18:58:52.954:     obs-webrtc.dll
18:58:52.954:     obs-vst.dll
18:58:52.954:     obs-transitions.dll
18:58:52.954:     obs-text.dll
18:58:52.954:     obs-qsv11.dll
18:58:52.954:     obs-outputs.dll
18:58:52.954:     obs-filters.dll
18:58:52.954:     obs-ffmpeg.dll
18:58:52.954:     obs-browser.dll
18:58:52.954:     obs-asio.dll
18:58:52.954:     logi_obs_plugin_x64.dll
18:58:52.954:     image-source.dll
18:58:52.954:     frontend-tools.dll
18:58:52.954:     decklink-output-ui.dll
18:58:52.954:     decklink-captions.dll
18:58:52.954:     coreaudio-encoder.dll
18:58:52.954: ---------------------------------
18:58:52.957: QWidget::setTabOrder: 'first' and 'second' must be in the same window
18:58:52.957: ==== Startup complete ===============================================
18:58:52.999: All scene data cleared
18:58:52.999: ------------------------------------------------
18:58:53.002: [asio source]: opening device: SERIES 102i/208i ASIO
18:58:53.002: [asio source]: Driver successfully removed
18:58:53.003: [asio source]: driver com interface opened
18:58:53.004: [asio source]:  channels in: 10, channels out: 4
18:58:53.005: [asio source]: 256 -> 256, preferred: 256, step: 0
18:58:53.012: [asio source]: Latencies: in = 300, out = 680
18:58:53.012: [asio source]: creating buffers (dummy): 4 channels, size: 256
18:58:53.034: [asio source]: Latencies: in = 300, out = 680
18:58:53.500: [asio source]: device opened but not started yet
18:58:53.507: [asio source]: clock: Internal (cur)
18:58:53.509: [asio source]: disposing buffers
18:58:53.509: [asio source]: creating buffers: 14, size: 256
18:58:53.520: [asio source]: input sample format: 18, output sample format: 18
18:58:53.520:  (19 == 32 bit float, 17 == 24 bit int, 18 == 32 bit int)
18:58:53.521: [asio source]: Latencies: in = 300, out = 680
18:58:53.521: [asio source]: 256 -> 256, preferred: 256, step: 0
18:58:53.521: [asio source]: starting
18:58:53.796: Switched to scene 'Scene'
18:58:53.796: ------------------------------------------------
18:58:53.796: Loaded scenes:
18:58:53.796: - scene 'Scene':
18:58:53.796:     - source: 'ASIO input' (asio_input_capture)
18:58:53.796: ------------------------------------------------
18:59:13.786: ==== Shutting down ==================================================

```

**Comment by pkviet** [comment]
Tascam device ?
I had shitty experience with their drivers.
I need to figure out a fix. But you can use 4.0.0 .
The 4.0.1 only differs in that it's preventing a crash for some devices by stalling the destruction of the asio source.
If you didn't experience any issues with 4.0.0 when exiting obs, you can stay with it and forget about 4.0.1 since the crash fix doesn't apply to your device.
I'll try to devise a solution which works for everybody later.

**Comment by jegyll** [comment]
@pkviet 
I am using asio plugin v 4.0.1.
It also crashes when OBS exits.

OS:Windows11/23H2/22631.2861
CPU:AMD Ryzen 3700X
GPU:RTA 2070SP
RAM:64GB
Audio IF:RME FireFace 802 (driver v.1.246 , hardware rev20)
OBS:v30.0.2

**Comment by pkviet** [comment]
> @pkviet 
> I am using asio plugin v 4.0.1.
> It also crashes when OBS exits.
> 
> OS:Windows11/23H2/22631.2861
> CPU:AMD Ryzen 3700X
> GPU:RTA 2070SP
> RAM:64GB
> Audio IF:RME FireFace 802 (driver v.1.246 , hardware rev20)
> OBS:v30.0.2

@jegyll  ok thanks, i'm gonna revert 4.0.1 if you can confirm 4.0.0 works.
Could you post the crash log ?

**Comment by pkviet** [comment]
@ApostolDmitry 
[win-asio.zip](https://github.com/pkviet/obs-asio/files/13795501/win-asio.zip)
here's a test dll with a potential fix to obs hanging on exit.
You need to remove the current obs-asio.dll (back it up) and extract the zip (the dll is named win-asio.dll instead of obs-asio.dll, no need to rename it; I just compiled it straight with visual studio).
@jegyll could you test too ? but you might have a different issue; i really need your crash log

**Comment by myrddin64** [comment]
> @ApostolDmitry [win-asio.zip](https://github.com/pkviet/obs-asio/files/13795501/win-asio.zip) here's a test dll with a potential fix to obs hanging on exit. You need to remove the current obs-asio.dll (back it up) and extract the zip (the dll is named win-asio.dll instead of obs-asio.dll, no need to rename it; I just compiled it straight with visual studio). @jegyll could you test too ? but you might have a different issue; i really need your crash log

Hey buddy, I just noticed you were working on this... I updated my bata to the current version you have... and I also started to have a repeating hang crash. So, I grabbed your dll and dropped it in to test and it does fix the hang crash... just letting you know.

**Comment by pkviet** [comment]
> > @ApostolDmitry [win-asio.zip](https://github.com/pkviet/obs-asio/files/13795501/win-asio.zip) here's a test dll with a potential fix to obs hanging on exit. You need to remove the current obs-asio.dll (back it up) and extract the zip (the dll is named win-asio.dll instead of obs-asio.dll, no need to rename it; I just compiled it straight with visual studio). @jegyll could you test too? but you might have a different issue; i really need your crash log
> 
> Hey buddy, I just noticed you were working on this... I updated my beta to the current version you have... and I also started to have a repeating hang crash. So, I grabbed your dll and dropped it in to test and it does fix the hang crash... just letting you know.

Thanks Myrddin.
Gonna make another release.

**Comment by myrddin64** [comment]
> > > @ApostolDmitry [win-asio.zip](https://github.com/pkviet/obs-asio/files/13795501/win-asio.zip) here's a test dll with a potential fix to obs hanging on exit. You need to remove the current obs-asio.dll (back it up) and extract the zip (the dll is named win-asio.dll instead of obs-asio.dll, no need to rename it; I just compiled it straight with visual studio). @jegyll could you test too? but you might have a different issue; i really need your crash log
> > 
> > 
> > Hey buddy, I just noticed you were working on this... I updated my beta to the current version you have... and I also started to have a repeating hang crash. So, I grabbed your dll and dropped it in to test and it does fix the hang crash... just letting you know.
> 
> Thanks Myrddin. Gonna make another release.

One other thing... I am about to head out, so I shit OBS down again and I got another crash but not on a hang... Sadly I missed the dump. And I cant get it to recreate... so?? when I get back I will open/close to see if I can repro for you. (few hours)

![image](https://github.com/pkviet/obs-asio/assets/92278129/7ce59b1a-014a-450d-bb56-867c02a719a7)

**Comment by myrddin64** [comment]
I have tried it 5 more times and it has not crashed agn... once I get back, I will give it another once over... it may have been me because I was moving things around in OBS... 

back later.

**Comment by pkviet** [comment]
I've made a new release, which should fix the hang and still prevent crashes.
https://github.com/pkviet/obs-asio/releases/tag/4.0.2

**Comment by ApostolDmitry** [comment]
@pkviet  Oh thanks, your path fixing my problem
