### ISSUE TITLE
Crackling sounds

### ISSUE THREAD

**Issue by shnaff** [pkviet/obs-asio#4]
I'm capturing the audio from ableton by using the asio source plugin for obs but now I get crackling in the audio only when obs is both running AND when I select "active device" under Tools > ASIO Device Settings. I have tried changing buffer sizes and sample rates, changing USB ports for my interface (Focusrite Scarlett 2i2), and optimizing windows for performance. Any help is appreciated!

**Comment by pkviet** [comment]
asio devices are exclusive ; this is a very well known limitation of the asio sdk.   
(some drivers allow multi-clients but they are exceedingly rare).
So you can NOT use your focusrite with ableton and obs at the same time and expect the two apps to work properly.   
If you want to  route audio from a DAW to obs, you'll need virtual audio drivers.
For instance, reaper has the rearoute virtual device. One would capture the focusrite in reaper and route to obs with rearoute + asio plugin.
Maybe this is possible with ableton; I can't say, i don't own a copy.
