### ISSUE TITLE
cant see the plugin in sources 

### ISSUE THREAD

**Issue by isvein** [pkviet/obs-asio#5]
I installed the binary but cant see the ASIO source when I try to add a new source,
Tried both versions.
Is there anything Im missing?

OBS 22.0.1, tried both 64 and 32 bit
Windows 10, latest

**Comment by pkviet** [comment]
Hi,
thanks for the feedback. I indeed find issues with V2 but V1 installs and works fine. I've removed therefore the V2 installer.
Could you provide your log and retry with V1 ?
I'll upload V2 again once I solve the issue.

**Comment by isvein** [comment]
Thanks :) I tried again now and found the problem. 
The addon installs to "C:\Program Files\obs-studio" but my OBS, even the 64bit is installed in "C:\Program Files (x86)\obs-studio"

Moved the files from the x86 folder to where I have my OBS installed and then it shows up.

**Comment by baircave** [comment]
i'm having this exact same issue, nothing showing up in the Sources panel as was expected from the ReadMe. Any help would be greatly appreciated ^_^

**Comment by pkviet** [comment]
obs 22 + changed its install folder;  the plugin accordingly installs there. You must have an older obs version.
Easy solution: upgrade to obs 22

**Comment by baircave** [comment]
I have OBS 22.0.2 which is the latest one. Still no luck :/

**Comment by pkviet** [comment]
can you check whether the obs-asio.dll is in the plugins folder as well as the portaudio dll ? and upload your log

**Comment by baircave** [comment]
ah i didn't move everything over to the x86 folder. all good now, thanks!

**Comment by pkviet** [comment]
great
