### ISSUE TITLE
Can't see the plug-in in sources

### ISSUE THREAD

**Issue by CorpulentBrony** [pkviet/obs-asio#6]
I am having the exact same issue as #5 but none of the suggested fixes there are working.  I am using OBS 22.0.2 and have tried both the 1.1.0 release and the alpha release.  I have ensured the plugin files are installed in both the Program Files/obs-studio/64bit and the Program Files (x86)/obs-studio/64bit directories.

**Comment by pkviet** [comment]
Please post a log (check the help menu, and drag 'n drop the file here)

**Comment by CHEF-KOCH** [comment]
That's the problem, the OBS Studio x64 version is only installed into `C:\Program Files (x86)\obs-studio`, there is no `Program Files/obs-studio/64bit` dir. 

Remove OBS Studio, download the official installer, install it, start fresh. Make sure you start OBS as admin + start the x64 exe.

**Comment by pkviet** [comment]
Issue fixed with new installer script.

**Comment by CorpulentBrony** [comment]
Just a quick note to confirm that the issue is now fixed.  Thanks.
