### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by ToxMox** [pkviet/obs-asio#7]
Hey I just wanted to thank you for creating this. It has made my crazy audio setup quite a bit simpler.
Do you have a donation link or anything?

**Comment by pkviet** [comment]
you're welcome. My co-developper @Andersama  has a paypal if you want to offer him a burger : anderson.john.alexander@gmail.com

**Comment by ToxMox** [comment]
Consider it done :) 👍

**Comment by pkviet** [comment]
Andersama thanks you  ;)
