### ISSUE TITLE
OBS restart required after recording

### ISSUE THREAD

**Issue by dgmulf** [pkviet/obs-asio#8]
This plug-in works perfectly for me with one exception: after recording a single take, the ASIO sources are no longer active until I restart OBS.

**Comment by pkviet** [comment]
hi, I can't repro this bug.
we will need more info as to your hardware: what is your sound device ? drop a log too.
Seems like a botched asio driver
For more troubleshooting, go to obs discord server and ping pkv or Andersama (we're the developers)

**Comment by pkviet** [comment]
No news, so i'm closing.

**Comment by dgmulf** [comment]
Sorry for the lack of updates. I'm using an Audient iD22 on Windows 10 64-bit. I wouldn't be surprised if it's a problem with the ASIO driver; it's been finicky in the past. Here's a log:
[2018-11-25 10-39-23.txt](https://github.com/pkviet/obs-asio/files/2776192/2018-11-25.10-39-23.txt)

**Comment by dgmulf** [comment]
Thanks for the suggestion. I'll try this next time I need to use OBS.
